# Build and test .NET Core projects in Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pr:
- main

variables:
  # Define CI env var to match other CI systems
  # Enables WarningsAsErrors in Directory.Build.props
  CI: "true"

strategy:
  matrix:
    linux:
      imageName: ubuntu-latest
    # Uncomment and increase maxParallel to test on macOS:
    # mac:
    #   imageName: macOS-latest
    windows:
      imageName: windows-latest
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- script: dotnet test --settings TestCoverage.runsettings
  displayName: dotnet test
